//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.CP.Server.Model.Auction.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201604261235548_AuctionInitial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201604261235548_AuctionInitial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.Auction.Migrations.201604261235548_AuctionInitial", typeof(_201604261235548_AuctionInitial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO1d3W7cOJa+X2DfoVBXu4OMy3ZPDzKBPYO0k8wYnaSN2GnsnaGoaFtolVQjqdI2FvNke7GPtK+wpEhJ/Dn8kyhVORECOLZIHp5Dfufw7xzy//7nf8/+9rhJF19RUSZ5dr48OTpeLlAW5+skuz9f7qq7P75c/u2v//5vZ2/Xm8fFr02+H0g+XDIrz5cPVbV9tVqV8QPaROXRJomLvMzvqqM436yidb46PT7+y+rkZIUwiSWmtVicfdplVbJB9R/4z4s8i9G22kXph3yN0pJ9xynXNdXFx2iDym0Uo/MlzhAfXaMC83xU5z56vYsrzNURplKhx6pcLl6nSYQ5u0bp3XIRZVleRSTHq88luq6KPLu/3uIPUXrztEU4312UlojJ86rL7ira8SkRbdUVbEjFu7LKN54ET35gbbWSi/dq8WXblrg13+JWr56I1HWLni9Z0/2UrJcLubpXF2lBspqavCv/YqHN9aLFDYYX/venF4uLXVrtCnSe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
